In [22]:
import numpy as np

np.random.seed(1)

In [23]:
# channels, width, height
input_img = np.random.randint(low=1, high=3, size=(2,3,4))#np.random.rand(2,3,4)
input_size = input_img.shape
input_img

array([[[2, 2, 1, 1],
        [2, 2, 2, 2],
        [2, 1, 1, 2]],

       [[1, 2, 2, 1],
        [1, 2, 1, 1],
        [1, 2, 1, 1]]])

In [24]:
num_kernels = 3
kernel_size = 3
kernels = np.random.randint(low=0, high=3, size=(num_kernels,kernel_size,kernel_size))#np.random.rand(2,3,4)
kernels

array([[[0, 2, 0],
        [1, 2, 2],
        [0, 1, 1]],

       [[2, 0, 2],
        [1, 1, 1],
        [1, 2, 1]],

       [[1, 0, 0],
        [1, 0, 0],
        [1, 2, 1]]])

In [25]:
def apply_1d_padding(input_img, kernel_size):
    pad = kernel_size//2
    return np.concatenate([np.zeros(pad), input_img, np.zeros(pad)])

def apply_2d_padding(input_img, kernel_size):
    pad_side = np.stack([apply_1d_padding(row, kernel_size) for row in input_img])
    width = pad_side.shape[1]
    pad_tops = np.vstack([np.zeros(width), pad_side,np.zeros(width)])
    return pad_tops

#
input_pad = np.stack([apply_2d_padding(channel, kernel_size) for channel in input_img])

In [27]:
# Forward pass
output = np.zeros(shape=(num_kernels, input_size[1], input_size[2]))

for i in range(input_img.shape[0]):
    for k in range(num_kernels): #output channels
        for i_w in range(input_img.shape[1]): #img width
            for i_h in range(input_img.shape[2]): # img height
                for k_w in range(kernel_size):
                    for k_h in range(kernel_size):
                        output[k][i_w][i_h] += kernels[k][k_w][k_h] * input_pad[i][i_w+k_w][i_h+k_h]

output

array([[[21., 24., 20., 10.],
        [26., 30., 27., 16.],
        [18., 21., 19., 14.]],

       [[17., 24., 22., 14.],
        [24., 33., 32., 20.],
        [14., 20., 22., 11.]],

       [[10., 17., 17., 12.],
        [ 9., 17., 18., 14.],
        [ 0.,  6.,  7.,  5.]]])

In [ ]:
# Backward Pass
